"use strict";
exports.__esModule = true;
var Product_1 = require("./Product");
var ProductService_1 = require("./ProductService");
var _productService = new ProductService_1.ProductService();
var result;
result = _productService.getById(2);
var p = new Product_1.Product();
p.name = "Iphone 6";
p.price = 1000000;
p.category = "Telefon";
_productService.saveProduct(p);
result = _productService.getProducts();
console.log(result);
_productService.deleteProduct(p);
result = _productService.getProducts();
console.log(result);
